---
version: '3'

tasks:
  build:ubuntu:
    desc: Build Ubuntu Nomad template
    cmds:
      - |
        fish -c "source scripts/set-proxmox-password.fish && packer build -var-file=packer/variables/common.pkrvars.hcl -var-file=packer/variables/proxmox-host1.pkrvars.hcl packer/templates/ubuntu/ubuntu-nomad.pkr.hcl"

  # build:alpine:
  #   desc: Build Alpine Nomad template
  #   cmds:
  #     - |
  #       bash -lc "PKR_VAR_clone_vm_id=\${PKR_VAR_clone_vm_id:-9001} PACKER_LOG=1 PKR_VAR_ssh_username=\${PKR_VAR_ssh_username:-\"$ALPINE_SSH_USERNAME\"} packer build packer/templates/alpine/alpine.pkr.hcl"

  build:base:
    desc: Build Ubuntu base image
    cmds:
      - |
        fish -c "source scripts/set-proxmox-password.fish && packer build -var-file=packer/variables/common.pkrvars.hcl -var-file=packer/variables/proxmox-host1.pkrvars.hcl packer/templates/ubuntu/ubuntu-bare-minimum.pkr.hcl"

  build:minimal:
    desc: Build minimal Ubuntu cloud agent template (qga + cloud-init)
    cmds:
      - |
        fish -c "source scripts/set-proxmox-password.fish && packer build -var-file=packer/variables/common.pkrvars.hcl -var-file=packer/variables/proxmox-host1.pkrvars.hcl packer/templates/ubuntu/ubuntu-qemu-agent.pkr.hcl"

  build:debian:base:
    desc: Create Debian 12 Cloud Base Template (VM 9400)
    cmds:
      - bash packer/scripts/create-debian-cloud-base.sh 10.0.0.21

  build:debian:client:
    desc: Build Debian Nomad Client template
    cmds:
      - |
        fish -c "source scripts/set-proxmox-password.fish && packer build -var-file=packer/variables/common.pkrvars.hcl -var-file=packer/variables/proxmox-host1.pkrvars.hcl packer/templates/debian/debian-nomad-client.pkr.hcl"

  build:debian:server:
    desc: Build Debian Nomad Server template
    cmds:
      - |
        fish -c "source scripts/set-proxmox-password.fish && packer build -var-file=packer/variables/common.pkrvars.hcl -var-file=packer/variables/proxmox-host1.pkrvars.hcl packer/templates/debian/debian-nomad-server.pkr.hcl"

  validate:
    desc: Validate all Packer templates
    cmds:
      - packer validate packer/templates/ubuntu/ubuntu-nomad.pkr.hcl
      # - packer validate packer/templates/alpine/alpine.pkr.hcl
      - packer validate packer/templates/ubuntu/ubuntu-bare-minimum.pkr.hcl
      - packer validate packer/templates/debian/debian-nomad-client.pkr.hcl
      - packer validate packer/templates/debian/debian-nomad-server.pkr.hcl

  fmt:
    desc: Format all Packer templates
    cmds:
      - packer fmt -recursive packer/templates/

  tf:init:
    desc: "Initialize Terraform workspace"
    cmds:
      - |
        cd terraform/environments/dev && terraform init

  tf:plan:
    desc: "Terraform plan"
    cmds:
      - |
        cd terraform/environments/dev && terraform plan

  tf:apply:
    desc: "Terraform apply (will create VMs)"
    cmds:
      - |
        cd terraform/environments/dev && terraform init && terraform apply -auto-approve

  tf:destroy:
    desc: "Terraform destroy (will tear down VMs created by Terraform)"
    cmds:
      - |
        cd terraform/environments/dev && terraform init && terraform destroy -auto-approve

  setup:volumes:
    desc: "Create required host volumes on Nomad clients"
    cmds:
      - |
        ssh ubuntu@10.0.0.60 "sudo mkdir -p /mnt/prometheus_data /mnt/grafana_data && sudo chmod 777 /mnt/prometheus_data /mnt/grafana_data"
      - |
        ssh ubuntu@10.0.0.61 "sudo mkdir -p /mnt/prometheus_data /mnt/grafana_data && sudo chmod 777 /mnt/prometheus_data /mnt/grafana_data"
      - echo "Host volumes created on both clients"

  deploy:
    desc: "Deploy all Nomad jobs in correct order"
    cmds:
      - |
        NOMAD_ADDR=http://10.0.0.50:4646 nomad job run jobs/system/traefik.nomad.hcl
      - |
        NOMAD_ADDR=http://10.0.0.50:4646 nomad job run jobs/services/prometheus.nomad.hcl
      - |
        NOMAD_ADDR=http://10.0.0.50:4646 nomad job run jobs/services/grafana.nomad.hcl
      - |
        NOMAD_ADDR=http://10.0.0.50:4646 nomad job run jobs/services/whoami.nomad.hcl
      - echo "All jobs deployed successfully"
